import { Geist, Geist_Mono } from "next/font/google"; //دة الاستيراد بتاع الخطوط
import "./globals.css";
import NavBar from "@/componant/header/header";
import Footer from "@/componant/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// دة بيتغير عادي حسب نوع الخط اللي انا عايزاه وهي شارحاه الساعة 12:50 اول محاضرة 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// بغير فيها براحتي زيها زي ال meta بتاعت ال html
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar/>
        <div>
        {children} 
        </div>
        <Footer/>
        {/* دي بتبقي شايلة الصفحة اللي انا واقفة عليها  */}
      </body>
    </html>
  );
}
